trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/nGratis.AI.Kvasir.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  displayName: Restore COP.Core packages
  inputs:
    script: '.paket\paket.exe restore'
    workingDirectory: '$(Build.Repository.LocalPath)/External/cop.core/Source'

- task: CmdLine@2
  displayName: Restore AI.Kvasir packages
  inputs:
    script: '.paket\paket.exe restore'
    workingDirectory: '$(Build.Repository.LocalPath)/Source'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
