trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/nGratis.AI.Kvasir.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  displayName: Restore COP.Core packages
  inputs:
    script: 'External\cop.core\Source\.paket\paket.exe restore'

- task: CmdLine@2
  displayName: Restore AI.Kvasir packages
  inputs:
    script: 'Source\.paket\paket.exe restore'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
