trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/nGratis.AI.Kvasir.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  displayName: 'Execute AppVeyor pre-build steps'
  inputs:
    script: 'appveyor_prebuild.cmd'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/bin/$(buildConfiguration)/*Test.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)/Source'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
